# Generated by Django 3.2.4 on 2021-07-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_auto_20210708_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharity',
            name='connection',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersponsor',
            name='connection',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercharity',
            name='description',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='usersponsor',
            name='description',
            field=models.TextField(max_length=2048),
        ),
    ]
