# Generated by Django 3.2.4 on 2021-07-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_auto_20210712_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_time',
            field=models.TextField(default='2021-07-17 11:53:22', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='request_time',
            field=models.TextField(default='2021-07-17 11:53:22', max_length=200),
            preserve_default=False,
        ),
    ]
